export const GET_ONEDAYWEATHERSUCCESS = 'GET_ONEDAYWEATHERSUCCESS';
export const GET_FIVEDAYBYTHREEHOURWEATHERSUCCESS = 'GET_FIVEDAYBYTHREEHOURWEATHERSUCCESS';
export const GET_REQUESTSSUCCESS = 'GET_REQUESTSSUCCESS';
export const GET_ANALYSISSUCCESS = 'GET_ANALYSISSUCCESS';
